-- 恐怖之眼血量翻倍，cd减半
TUNING.EYEOFTERROR_CHARGECD = TUNING.EYEOFTERROR_CHARGECD / 2
TUNING.EYEOFTERROR_MOUTHCHARGECD = TUNING.EYEOFTERROR_MOUTHCHARGECD / 2
TUNING.EYEOFTERROR_SPAWNCD = TUNING.EYEOFTERROR_SPAWNCD / 2
TUNING.EYEOFTERROR_FOCUSCD = TUNING.EYEOFTERROR_FOCUSCD / 2
TUNING.EYEOFTERROR_HEALTH = TUNING.EYEOFTERROR_HEALTH * 2

-- 双子魔眼血量翻倍，cd减半
TUNING.TWIN1_CHARGECD = TUNING.TWIN1_CHARGECD / 2
TUNING.TWIN1_MOUTHCHARGECD = TUNING.TWIN1_MOUTHCHARGECD / 2
TUNING.TWIN1_SPAWNCD = TUNING.EYEOFTERROR_SPAWNCD / 2
TUNING.TWIN1_FOCUSCD = TUNING.TWIN1_FOCUSCD / 2
TUNING.TWIN1_HEALTH = TUNING.TWIN1_HEALTH * 2

TUNING.TWIN2_CHARGECD = TUNING.TWIN2_CHARGECD / 2
TUNING.TWIN2_MOUTHCHARGECD = TUNING.TWIN2_MOUTHCHARGECD / 2
TUNING.TWIN2_SPAWNCD = TUNING.TWIN2_SPAWNCD / 2
TUNING.TWIN2_FOCUSCD = TUNING.TWIN2_FOCUSCD / 2
TUNING.TWIN2_HEALTH = TUNING.TWIN2_HEALTH * 2

-- AddPrefabPostInit(
--     "twinmanager",
--     function()
--         -- body
--     end
-- )

-- AddPrefabPostInit(
--     "terrarium",
--     function()
--         -- body
--     end
-- )
