return {
    MoreDataKeys = {
        "min_spacing",
        "nounlock",
        "numtogive",
        "builder_tag",
        "testfn",
        "product",
        "build_mode",
        "build_distance",

        "placer",
        "filter",
        "description",
        "canbuild",
        "sg_state",
        "no_deconstruction",
        "require_special_event",
        "dropitem",
        "actionstr",
        "manufactured",
    },
    -- {
    --     name = "wasphive_new",
    --     product = "wasphive",
    --     displayName = "杀人蜂巢",
    --     description = "wasphive_new",
    --     displayDesc = "我记得这里应该有个杀人蜂巢来着?",
    --     ingredients = {
    --         boards = 2,
    --         honeycomb = 1,
    --         killerbee = 4,
    --     },
    --     tech = TECH.SCIENCE_TWO,
    --     placer = "wasphive_placer",

    --     filters = {"STRUCTURES", "GARDENING"},
    --     min_spacing = 2.5,
    --     atlas = "images/wasphive.xml",
    --     image = "wasphive.tex",
    -- },
    -- {
    --     name = "seed_new",
    --     product = "seeds",
    --     displayName = "普通种子",
    --     description = "seed_new",
    --     displayDesc = "普通种子收集起来好麻烦啊",
    --     ingredients = {
    --         acorn = 10,
    --         pinecone = 10,
    --     },
    --     tech = TECH.SCIENCE_TWO,
    --     numtogive = 10,
    --     filters = {"GARDENING"},
    --     atlas = "images/seed.xml",
    --     image = "seed.tex",
    -- },
    Recipes = {
        {
            name = "player_tomb2hm",
            product = "player_tomb2hm",
            description = "player_tomb2hm",
            displayName_ch = "哀悼之穴",
            displayName_en = "player tomb",
            displayDesc_ch = "为死去的队友种点什么吧",
            displayDesc_en = "platn something for dead player",
            ingredients = {
                cutstone = 3,
                petals_evil = 4,
                boards = 3,
                reviver = 1,
            },
            tech = TECH.NONE,
            placer = "player_tomb2hm_placer",
            filters = {"STRUCTURES", "GARDENING"},
            min_spacing = 3,
            atlas = "images/tomb_repair.xml",
            image = "tomb_repair.tex",
            openFunc = {"enable easy mode", "player_tomb"},
        },
    },
}