local PLANT_DEFS = require("prefabs/farm_plant_defs").PLANT_DEFS

local function MakeGrowTimes(germination_min, germination_max, full_grow_min, full_grow_max)
	local grow_time = {}

	grow_time.seed		= {germination_min, germination_max}
	grow_time.sprout	= {full_grow_min * 0.5, full_grow_max * 0.5}
	grow_time.small		= {full_grow_min * 0.3, full_grow_max * 0.3}
	grow_time.med		= {full_grow_min * 0.2, full_grow_max * 0.2}
	grow_time.full		= 4 * TUNING.TOTAL_DAY_TIME
	grow_time.oversized	= 6 * TUNING.TOTAL_DAY_TIME
	grow_time.regrow	= {4 * TUNING.TOTAL_DAY_TIME, 5 * TUNING.TOTAL_DAY_TIME}

	return grow_time
end

local plantregistryinfo = {
	{text = "seed", anim = "crop_seed", grow_anim = "grow_seed", learnseed = true, growing = true},
	{text = "sprout", anim = "crop_sprout", grow_anim = "grow_sprout", growing = true},
	{text = "small", anim = "crop_small", grow_anim = "grow_small", growing = true},
	{text = "medium", anim = "crop_med", grow_anim = "grow_med", growing = true},
	{text = "grown", anim = "crop_full", grow_anim = "grow_full", revealplantname = true, fullgrown = true},
	{text = "oversized", anim = "crop_oversized", grow_anim = "grow_oversized", revealplantname = true, fullgrown = true, hidden = true},
	{text = "rotting", anim = "crop_rot", grow_anim = "grow_rot", stagepriority = -100, is_rotten = true, hidden = true},
	{text = "oversized_rotting", anim = "crop_rot_oversized", grow_anim = "grow_rot_oversized", stagepriority = -100, is_rotten = true, hidden = true},
}

local sounds = {
	grow_oversized = "farming/common/farm/potato/grow_oversized",
	grow_full = "farming/common/farm/grow_full",
	grow_rot = "farming/common/farm/rot",
}

-- Nutrients
local S = TUNING.FARM_PLANT_CONSUME_NUTRIENT_LOW
local M = TUNING.FARM_PLANT_CONSUME_NUTRIENT_MED
local L = TUNING.FARM_PLANT_CONSUME_NUTRIENT_HIGH

SEEDS_DEFS = {
	honor_seeds	= {
		grow_time   = MakeGrowTimes(12 * TUNING.SEG_TIME, 16 * TUNING.SEG_TIME, 0, 0),
		moisture	= {drink_rate = TUNING.FARM_PLANT_DRINK_MED, min_percent = TUNING.FARM_PLANT_DROUGHT_TOLERANCE},
		good_seasons = {autumn = true, spring = true},
		nutrient_consumption = {2, 2, 2},
		nutrient_restoration = {true, true, true},
		max_killjoys_tolerance	= TUNING.FARM_PLANT_KILLJOY_TOLERANCE,
		is_randomseed = true,
		sounds = sounds,
		prefab = "farm_plant_honor_seeds",
		seed = "honor_seeds",
		plant_type_tag = "farm_plant_randomseed",
		family_min_count = 0,
	},
	terror_seeds = {
		grow_time = MakeGrowTimes(12 * TUNING.SEG_TIME, 16 * TUNING.SEG_TIME, 0, 0),
		moisture = {drink_rate = TUNING.FARM_PLANT_DRINK_MED, min_percent = TUNING.FARM_PLANT_DROUGHT_TOLERANCE},
		good_seasons = {autumn = true, spring = true},
		nutrient_consumption = {2, 2, 2},
		nutrient_restoration = {true, true, true},
		max_killjoys_tolerance = TUNING.FARM_PLANT_KILLJOY_TOLERANCE,
		is_randomseed = true,
		sounds = sounds,
		prefab = "farm_plant_terror_seeds",
		seed = "terror_seeds",
		plant_type_tag = "farm_plant_randomseed",
		family_min_count = 0,
	}
}

PLANT_DEFS.honor_coconut = {
	build = "farm_plant_honor_coconut",
	bank = "farm_plant_honor_coconut",
	grow_time = MakeGrowTimes(12 * TUNING.SEG_TIME, 16 * TUNING.SEG_TIME, 4 * TUNING.TOTAL_DAY_TIME, 7 * TUNING.TOTAL_DAY_TIME),
	moisture = {drink_rate = TUNING.FARM_PLANT_DRINK_LOW, min_percent = TUNING.FARM_PLANT_DROUGHT_TOLERANCE},
	nutrient_consumption = {0, 0, M},
	nutrient_restoration = {true, true, nil},
	max_killjoys_tolerance = TUNING.FARM_PLANT_KILLJOY_TOLERANCE,
	good_seasons = {spring = true, summer = true},
	weight_data = {384.59, 662.77, .18},
	sounds = sounds,
	prefab = "farm_plant_honor_coconut",
	product = "honor_coconut",
	product_oversized = "honor_coconut_oversized",
	seed = "honor_coconut_seeds",
	plant_type_tag = "honor_coconut",
	loot_oversized_rot = {"spoiled_food", "spoiled_food", "spoiled_food", "honor_coconut_seeds", "fruitfly", "fruitfly"},
	family_min_count = TUNING.FARM_PLANT_SAME_FAMILY_MIN,
	family_check_dist = TUNING.FARM_PLANT_SAME_FAMILY_RADIUS,
	stage_netvar = net_tinybyte,
	plantregistryinfo = plantregistryinfo,
	plantregistrywidget = "widgets/redux/farmplantpage",
	plantregistrysummarywidget = "widgets/redux/farmplantsummarywidget",
	pictureframeanim = {anim = "emoteXL_loop_dance0", time = 7*FRAMES},
	honor_plant = true,
	honor_weight = 2,
	terror_plant = false,
	terror_weight = 0,

	modded = true,
}

PLANT_DEFS.honor_tea = {
	build = "farm_plant_honor_tea",
	bank = "farm_plant_honor_tea",
	grow_time = MakeGrowTimes(12 * TUNING.SEG_TIME, 16 * TUNING.SEG_TIME, 4 * TUNING.TOTAL_DAY_TIME, 7 * TUNING.TOTAL_DAY_TIME),
	moisture = {drink_rate = TUNING.FARM_PLANT_DRINK_LOW, min_percent = TUNING.FARM_PLANT_DROUGHT_TOLERANCE},
	nutrient_consumption = {0, L, 0},
	nutrient_restoration = {nil, true, nil},
	max_killjoys_tolerance = TUNING.FARM_PLANT_KILLJOY_TOLERANCE,
	good_seasons = {autumn = true, spring = true},
	weight_data = {384.59, 662.77, .18},
	sounds = sounds,
	prefab = "farm_plant_honor_tea",
	product = "honor_tea",
	product_oversized = "honor_tea_oversized",
	seed = "honor_tea_seeds",
	plant_type_tag = "honor_tea",
	loot_oversized_rot = {"spoiled_food", "spoiled_food", "spoiled_food", "honor_tea_seeds", "fruitfly", "fruitfly"},
	family_min_count = TUNING.FARM_PLANT_SAME_FAMILY_MIN,
	family_check_dist = TUNING.FARM_PLANT_SAME_FAMILY_RADIUS,
	stage_netvar = net_tinybyte,
	plantregistryinfo = plantregistryinfo,
	plantregistrywidget = "widgets/redux/farmplantpage",
	plantregistrysummarywidget = "widgets/redux/farmplantsummarywidget",
	pictureframeanim = {anim = "emoteXL_loop_dance0", time = 7*FRAMES},
	honor_plant = true,
	honor_weight = 1,
	terror_plant = false,
	terror_weight = 0,

	modded = true,
}

PLANT_DEFS.honor_rice = {
	build = "farm_plant_honor_rice",
	bank = "farm_plant_honor_rice",
	grow_time = MakeGrowTimes(12 * TUNING.SEG_TIME, 16 * TUNING.SEG_TIME, 4 * TUNING.TOTAL_DAY_TIME, 7 * TUNING.TOTAL_DAY_TIME),
	moisture = {drink_rate = TUNING.FARM_PLANT_DRINK_LOW, min_percent = TUNING.FARM_PLANT_DROUGHT_TOLERANCE},
	nutrient_consumption = {0, M, 0},
	nutrient_restoration = {true, nil, true},
	max_killjoys_tolerance = TUNING.FARM_PLANT_KILLJOY_TOLERANCE,
	good_seasons = {spring = true, summer = true},
	weight_data = {384.59, 662.77, .18},
	sounds = sounds,
	prefab = "farm_plant_honor_rice",
	product = "honor_rice",
	product_oversized = "honor_rice_oversized",
	seed = "honor_rice_seeds",
	plant_type_tag = "honor_rice",
	loot_oversized_rot = {"spoiled_food", "spoiled_food", "spoiled_food", "honor_rice_seeds", "fruitfly", "fruitfly"},
	family_min_count = TUNING.FARM_PLANT_SAME_FAMILY_MIN,
	family_check_dist = TUNING.FARM_PLANT_SAME_FAMILY_RADIUS,
	stage_netvar = net_tinybyte,
	plantregistryinfo = plantregistryinfo,
	plantregistrywidget = "widgets/redux/farmplantpage",
	plantregistrysummarywidget = "widgets/redux/farmplantsummarywidget",
	pictureframeanim = {anim = "emoteXL_loop_dance0", time = 7*FRAMES},
	honor_plant = true,
	honor_weight = 1,
	terror_plant = false,
	terror_weight = 0,

	modded = true,
}

PLANT_DEFS.honor_wheat = {
	build = "farm_plant_honor_wheat",
	bank = "farm_plant_honor_wheat",
	grow_time = MakeGrowTimes(12 * TUNING.SEG_TIME, 16 * TUNING.SEG_TIME, 4 * TUNING.TOTAL_DAY_TIME, 7 * TUNING.TOTAL_DAY_TIME),
	moisture = {drink_rate = TUNING.FARM_PLANT_DRINK_LOW, min_percent = TUNING.FARM_PLANT_DROUGHT_TOLERANCE},
	nutrient_consumption = {S, 0, S},
	nutrient_restoration = {nil, true, nil},
	max_killjoys_tolerance = TUNING.FARM_PLANT_KILLJOY_TOLERANCE,
	good_seasons = {autumn = true, spring = true, summer = true},
	weight_data = {384.59, 662.77, .18},
	sounds = sounds,
	prefab = "farm_plant_honor_wheat",
	product = "honor_wheat",
	product_oversized = "honor_wheat_oversized",
	seed = "honor_wheat_seeds",
	plant_type_tag = "honor_wheat",
	loot_oversized_rot = {"spoiled_food", "spoiled_food", "spoiled_food", "honor_wheat_seeds", "fruitfly", "fruitfly"},
	family_min_count = TUNING.FARM_PLANT_SAME_FAMILY_MIN,
	family_check_dist = TUNING.FARM_PLANT_SAME_FAMILY_RADIUS,
	stage_netvar = net_tinybyte,
	plantregistryinfo = plantregistryinfo,
	plantregistrywidget = "widgets/redux/farmplantpage",
	plantregistrysummarywidget = "widgets/redux/farmplantsummarywidget",
	pictureframeanim = {anim = "emoteXL_loop_dance0", time = 7*FRAMES},
	honor_plant = true,
	honor_weight = 1,
	terror_plant = false,
	terror_weight = 0,

	modded = true,
}

PLANT_DEFS.honor_goldenlanternfruit = {
	build = "farm_plant_honor_goldenlanternfruit",
	bank = "farm_plant_honor_goldenlanternfruit",
	grow_time = MakeGrowTimes(12 * TUNING.SEG_TIME, 16 * TUNING.SEG_TIME, 4 * TUNING.TOTAL_DAY_TIME, 7 * TUNING.TOTAL_DAY_TIME),
	moisture = {drink_rate = TUNING.FARM_PLANT_DRINK_LOW, min_percent = TUNING.FARM_PLANT_DROUGHT_TOLERANCE},
	nutrient_consumption = {S, S, 0},
	nutrient_restoration = {nil, nil, true},
	max_killjoys_tolerance = TUNING.FARM_PLANT_KILLJOY_TOLERANCE,
	good_seasons = {autumn = true, spring = true, summer = true},
	weight_data = {384.59, 662.77, .18},
	sounds = sounds,
	prefab = "farm_plant_honor_goldenlanternfruit",
	product = "honor_goldenlanternfruit",
	product_oversized = "honor_goldenlanternfruit_oversized",
	seed = "honor_goldenlanternfruit_seeds",
	plant_type_tag = "honor_goldenlanternfruit",
	loot_oversized_rot = {"spoiled_food", "spoiled_food", "spoiled_food", "honor_goldenlanternfruit_seeds", "fruitfly", "fruitfly"},
	family_min_count = TUNING.FARM_PLANT_SAME_FAMILY_MIN,
	family_check_dist = TUNING.FARM_PLANT_SAME_FAMILY_RADIUS,
	stage_netvar = net_tinybyte,
	plantregistryinfo = plantregistryinfo,
	plantregistrywidget = "widgets/redux/farmplantpage",
	plantregistrysummarywidget = "widgets/redux/farmplantsummarywidget",
	pictureframeanim = {anim = "emoteXL_loop_dance0", time = 7*FRAMES},
	honor_plant = true,
	honor_weight = 1,
	terror_plant = false,
	terror_weight = 0,

	modded = true,
}

PLANT_DEFS.honor_aloe = {
	build = "farm_plant_honor_aloe",
	bank = "farm_plant_honor_aloe",
	grow_time = MakeGrowTimes(12 * TUNING.SEG_TIME, 16 * TUNING.SEG_TIME, 4 * TUNING.TOTAL_DAY_TIME, 7 * TUNING.TOTAL_DAY_TIME),
	moisture = {drink_rate = TUNING.FARM_PLANT_DRINK_LOW, min_percent = TUNING.FARM_PLANT_DROUGHT_TOLERANCE},
	nutrient_consumption = {L, 0, 0},
	nutrient_restoration = {nil, true, true},
	max_killjoys_tolerance = TUNING.FARM_PLANT_KILLJOY_TOLERANCE,
	good_seasons = {autumn = true, winter = true},
	weight_data = {384.59, 662.77, .18},
	sounds = sounds,
	prefab = "farm_plant_honor_aloe",
	product = "honor_aloe",
	product_oversized = "honor_aloe_oversized",
	seed = "honor_aloe_seeds",
	plant_type_tag = "honor_aloe",
	loot_oversized_rot = {"spoiled_food", "spoiled_food", "spoiled_food", "honor_aloe_seeds", "fruitfly", "fruitfly"},
	family_min_count = TUNING.FARM_PLANT_SAME_FAMILY_MIN,
	family_check_dist = TUNING.FARM_PLANT_SAME_FAMILY_RADIUS,
	stage_netvar = net_tinybyte,
	plantregistryinfo = plantregistryinfo,
	plantregistrywidget = "widgets/redux/farmplantpage",
	plantregistrysummarywidget = "widgets/redux/farmplantsummarywidget",
	pictureframeanim = {anim = "emoteXL_loop_dance0", time = 7*FRAMES},
	honor_plant = true,
	honor_weight = 1,
	terror_plant = false,
	terror_weight = 0,

	modded = true,
}

PLANT_DEFS.honor_hamimelon = {
	build = "farm_plant_honor_hamimelon",
	bank = "farm_plant_honor_hamimelon",
	grow_time = MakeGrowTimes(12 * TUNING.SEG_TIME, 16 * TUNING.SEG_TIME, 4 * TUNING.TOTAL_DAY_TIME, 7 * TUNING.TOTAL_DAY_TIME),
	moisture = {drink_rate = TUNING.FARM_PLANT_DRINK_LOW, min_percent = TUNING.FARM_PLANT_DROUGHT_TOLERANCE},
	nutrient_consumption = {0, 0, L},
	nutrient_restoration = {true, true, nil},
	max_killjoys_tolerance = TUNING.FARM_PLANT_KILLJOY_TOLERANCE,
	good_seasons = {summer = true, autumn = true},
	weight_data = {384.59, 662.77, .18},
	sounds = sounds,
	prefab = "farm_plant_honor_hamimelon",
	product = "honor_hamimelon",
	product_oversized = "honor_hamimelon_oversized",
	seed = "honor_hamimelon_seeds",
	plant_type_tag = "honor_hamimelon",
	loot_oversized_rot = {"spoiled_food", "spoiled_food", "spoiled_food", "honor_hamimelon_seeds", "fruitfly", "fruitfly"},
	family_min_count = TUNING.FARM_PLANT_SAME_FAMILY_MIN,
	family_check_dist = TUNING.FARM_PLANT_SAME_FAMILY_RADIUS,
	stage_netvar = net_tinybyte,
	plantregistryinfo = plantregistryinfo,
	plantregistrywidget = "widgets/redux/farmplantpage",
	plantregistrysummarywidget = "widgets/redux/farmplantsummarywidget",
	pictureframeanim = {anim = "emoteXL_loop_dance0", time = 7*FRAMES},
	honor_plant = true,
	honor_weight = 1,
	terror_plant = false,
	terror_weight = 0,

	modded = true,
}

PLANT_DEFS.honor_nut = {
	build = "farm_plant_honor_nut",
	bank = "farm_plant_honor_nut",
	grow_time = MakeGrowTimes(12 * TUNING.SEG_TIME, 16 * TUNING.SEG_TIME, 4 * TUNING.TOTAL_DAY_TIME, 7 * TUNING.TOTAL_DAY_TIME),
	moisture = {drink_rate = TUNING.FARM_PLANT_DRINK_LOW, min_percent = TUNING.FARM_PLANT_DROUGHT_TOLERANCE},
	nutrient_consumption = {S, S, 0},
	nutrient_restoration = {nil, nil, true},
	max_killjoys_tolerance = TUNING.FARM_PLANT_KILLJOY_TOLERANCE,
	good_seasons = {autumn = true, winter = true, spring = true},
	weight_data = {384.59, 662.77, .18},
	sounds = sounds,
	prefab = "farm_plant_honor_nut",
	product = "honor_nut",
	product_oversized = "honor_nut_oversized",
	seed = "honor_nut_seeds",
	plant_type_tag = "honor_nut",
	loot_oversized_rot = {"spoiled_food", "spoiled_food", "spoiled_food", "honor_nut_seeds", "fruitfly", "fruitfly"},
	family_min_count = TUNING.FARM_PLANT_SAME_FAMILY_MIN,
	family_check_dist = TUNING.FARM_PLANT_SAME_FAMILY_RADIUS,
	stage_netvar = net_tinybyte,
	plantregistryinfo = plantregistryinfo,
	plantregistrywidget = "widgets/redux/farmplantpage",
	plantregistrysummarywidget = "widgets/redux/farmplantsummarywidget",
	pictureframeanim = {anim = "emoteXL_loop_dance0", time = 7*FRAMES},
	honor_plant = true,
	honor_weight = 1,
	terror_plant = false,
	terror_weight = 0,

	modded = true,
}


PLANT_DEFS.terror_snakeskinfruit = {
	build = "farm_plant_terror_snakeskinfruit",
	bank = "farm_plant_terror_snakeskinfruit",
	grow_time = MakeGrowTimes(12 * TUNING.SEG_TIME, 16 * TUNING.SEG_TIME, 4 * TUNING.TOTAL_DAY_TIME, 7 * TUNING.TOTAL_DAY_TIME),
	moisture = {drink_rate = TUNING.FARM_PLANT_DRINK_LOW, min_percent = TUNING.FARM_PLANT_DROUGHT_TOLERANCE},
	nutrient_consumption = {0, S, S},
	nutrient_restoration = {true, nil, nil},
	max_killjoys_tolerance = TUNING.FARM_PLANT_KILLJOY_TOLERANCE,
	good_seasons = {autumn = true, summer = true, winter = true},
	weight_data = {384.59, 662.77, .18},
	sounds = sounds,
	prefab = "farm_plant_terror_snakeskinfruit",
	product = "terror_snakeskinfruit",
	product_oversized = "terror_snakeskinfruit_oversized",
	seed = "terror_snakeskinfruit_seeds",
	plant_type_tag = "terror_snakeskinfruit",
	loot_oversized_rot = {"spoiled_food", "spoiled_food", "spoiled_food", "terror_snakeskinfruit_seeds", "fruitfly", "fruitfly"},
	family_min_count = TUNING.FARM_PLANT_SAME_FAMILY_MIN,
	family_check_dist = TUNING.FARM_PLANT_SAME_FAMILY_RADIUS,
	stage_netvar = net_tinybyte,
	plantregistryinfo = plantregistryinfo,
	plantregistrywidget = "widgets/redux/farmplantpage",
	plantregistrysummarywidget = "widgets/redux/farmplantsummarywidget",
	pictureframeanim = {anim = "emoteXL_loop_dance0", time = 7*FRAMES},
	honor_plant = false,
	honor_weight = 0,
	terror_plant = true,
	terror_weight = 1,

	modded = true,
}

PLANT_DEFS.terror_blueberry = {
	build = "farm_plant_terror_blueberry",
	bank = "farm_plant_terror_blueberry",
	grow_time = MakeGrowTimes(12 * TUNING.SEG_TIME, 16 * TUNING.SEG_TIME, 4 * TUNING.TOTAL_DAY_TIME, 7 * TUNING.TOTAL_DAY_TIME),
	moisture = {drink_rate = TUNING.FARM_PLANT_DRINK_LOW, min_percent = TUNING.FARM_PLANT_DROUGHT_TOLERANCE},
	nutrient_consumption = {0, M, 0},
	nutrient_restoration = {true, nil, true},
	max_killjoys_tolerance = TUNING.FARM_PLANT_KILLJOY_TOLERANCE,
	good_seasons = {autumn = true, summer = true, winter = true},
	weight_data = {384.59, 662.77, .18},
	sounds = sounds,
	prefab = "farm_plant_terror_blueberry",
	product = "terror_blueberry",
	product_oversized = "terror_blueberry_oversized",
	seed = "terror_blueberry_seeds",
	plant_type_tag = "terror_blueberry",
	loot_oversized_rot = {"spoiled_food", "spoiled_food", "spoiled_food", "terror_blueberry_seeds", "fruitfly", "fruitfly"},
	family_min_count = TUNING.FARM_PLANT_SAME_FAMILY_MIN,
	family_check_dist = TUNING.FARM_PLANT_SAME_FAMILY_RADIUS,
	stage_netvar = net_tinybyte,
	plantregistryinfo = plantregistryinfo,
	plantregistrywidget = "widgets/redux/farmplantpage",
	plantregistrysummarywidget = "widgets/redux/farmplantsummarywidget",
	pictureframeanim = {anim = "emoteXL_loop_dance0", time = 7*FRAMES},
	honor_plant = false,
	honor_weight = 0,
	terror_plant = true,
	terror_weight = 2,

	modded = true,
}

PLANT_DEFS.terror_ginger = {
	build = "farm_plant_terror_ginger",
	bank = "farm_plant_terror_ginger",
	grow_time = MakeGrowTimes(12 * TUNING.SEG_TIME, 16 * TUNING.SEG_TIME, 4 * TUNING.TOTAL_DAY_TIME, 7 * TUNING.TOTAL_DAY_TIME),
	moisture = {drink_rate = TUNING.FARM_PLANT_DRINK_LOW, min_percent = TUNING.FARM_PLANT_DROUGHT_TOLERANCE},
	nutrient_consumption = {M, 0, 0},
	nutrient_restoration = {nil, true, true},
	max_killjoys_tolerance = TUNING.FARM_PLANT_KILLJOY_TOLERANCE,
	good_seasons = {autumn = true, winter = true},
	weight_data = {384.59, 662.77, .18},
	sounds = sounds,
	prefab = "farm_plant_terror_ginger",
	product = "terror_ginger",
	product_oversized = "terror_ginger_oversized",
	seed = "terror_ginger_seeds",
	plant_type_tag = "terror_ginger",
	loot_oversized_rot = {"spoiled_food", "spoiled_food", "spoiled_food", "terror_ginger_seeds", "fruitfly", "fruitfly"},
	family_min_count = TUNING.FARM_PLANT_SAME_FAMILY_MIN,
	family_check_dist = TUNING.FARM_PLANT_SAME_FAMILY_RADIUS,
	stage_netvar = net_tinybyte,
	plantregistryinfo = plantregistryinfo,
	plantregistrywidget = "widgets/redux/farmplantpage",
	plantregistrysummarywidget = "widgets/redux/farmplantsummarywidget",
	pictureframeanim = {anim = "emoteXL_loop_dance0", time = 7*FRAMES},
	honor_plant = false,
	honor_weight = 0,
	terror_plant = true,
	terror_weight = 2,

	modded = true,
}

PLANT_DEFS.terror_lemon = {
	build = "farm_plant_terror_lemon",
	bank = "farm_plant_terror_lemon",
	grow_time = MakeGrowTimes(12 * TUNING.SEG_TIME, 16 * TUNING.SEG_TIME, 4 * TUNING.TOTAL_DAY_TIME, 7 * TUNING.TOTAL_DAY_TIME),
	moisture = {drink_rate = TUNING.FARM_PLANT_DRINK_LOW, min_percent = TUNING.FARM_PLANT_DROUGHT_TOLERANCE},
	nutrient_consumption = {0, M, 0},
	nutrient_restoration = {true, nil, true},
	max_killjoys_tolerance = TUNING.FARM_PLANT_KILLJOY_TOLERANCE,
	good_seasons = {autumn = true, spring = true, summer = true},
	weight_data = {384.59, 662.77, .18},
	sounds = sounds,
	prefab = "farm_plant_terror_lemon",
	product = "terror_lemon",
	product_oversized = "terror_lemon_oversized",
	seed = "terror_lemon_seeds",
	plant_type_tag = "terror_lemon",
	loot_oversized_rot = {"spoiled_food", "spoiled_food", "spoiled_food", "terror_lemon_seeds", "fruitfly", "fruitfly"},
	family_min_count = TUNING.FARM_PLANT_SAME_FAMILY_MIN,
	family_check_dist = TUNING.FARM_PLANT_SAME_FAMILY_RADIUS,
	stage_netvar = net_tinybyte,
	plantregistryinfo = plantregistryinfo,
	plantregistrywidget = "widgets/redux/farmplantpage",
	plantregistrysummarywidget = "widgets/redux/farmplantsummarywidget",
	pictureframeanim = {anim = "emoteXL_loop_dance0", time = 7*FRAMES},
	honor_plant = false,
	honor_weight = 0,
	terror_plant = true,
	terror_weight = 1,

	modded = true,
}

PLANT_DEFS.terror_litchi = {
	build = "farm_plant_terror_litchi",
	bank = "farm_plant_terror_litchi",
	grow_time = MakeGrowTimes(12 * TUNING.SEG_TIME, 16 * TUNING.SEG_TIME, 4 * TUNING.TOTAL_DAY_TIME, 7 * TUNING.TOTAL_DAY_TIME),
	moisture = {drink_rate = TUNING.FARM_PLANT_DRINK_LOW, min_percent = TUNING.FARM_PLANT_DROUGHT_TOLERANCE},
	nutrient_consumption = {M, 0, M},
	nutrient_restoration = {nil, true, nil},
	max_killjoys_tolerance = TUNING.FARM_PLANT_KILLJOY_TOLERANCE,
	good_seasons = {autumn = true, spring = true, summer = true},
	weight_data = {384.59, 662.77, .18},
	sounds = sounds,
	prefab = "farm_plant_terror_litchi",
	product = "terror_litchi",
	product_oversized = "terror_litchi_oversized",
	seed = "terror_litchi_seeds",
	plant_type_tag = "terror_litchi",
	loot_oversized_rot = {"spoiled_food", "spoiled_food", "spoiled_food", "terror_litchi_seeds", "fruitfly", "fruitfly"},
	family_min_count = TUNING.FARM_PLANT_SAME_FAMILY_MIN,
	family_check_dist = TUNING.FARM_PLANT_SAME_FAMILY_RADIUS,
	stage_netvar = net_tinybyte,
	plantregistryinfo = plantregistryinfo,
	plantregistrywidget = "widgets/redux/farmplantpage",
	plantregistrysummarywidget = "widgets/redux/farmplantsummarywidget",
	pictureframeanim = {anim = "emoteXL_loop_dance0", time = 7*FRAMES},
	honor_plant = false,
	honor_weight = 0,
	terror_plant = true,
	terror_weight = 1,

	modded = true,
}

PLANT_DEFS.terror_coffee = {
	build = "farm_plant_terror_coffee",
	bank = "farm_plant_terror_coffee",
	grow_time = MakeGrowTimes(12 * TUNING.SEG_TIME, 16 * TUNING.SEG_TIME, 4 * TUNING.TOTAL_DAY_TIME, 7 * TUNING.TOTAL_DAY_TIME),
	moisture = {drink_rate = TUNING.FARM_PLANT_DRINK_LOW, min_percent = TUNING.FARM_PLANT_DROUGHT_TOLERANCE},
	nutrient_consumption = {M, 0, 0},
	nutrient_restoration = {nil, true, true},
	max_killjoys_tolerance = TUNING.FARM_PLANT_KILLJOY_TOLERANCE,
	good_seasons = {autumn = true, spring = true, winter = true},
	weight_data = {384.59, 662.77, .18},
	sounds = sounds,
	prefab = "farm_plant_terror_coffee",
	product = "terror_coffee",
	product_oversized = "terror_coffee_oversized",
	seed = "terror_coffee_seeds",
	plant_type_tag = "terror_coffee",
	loot_oversized_rot = {"spoiled_food", "spoiled_food", "spoiled_food", "terror_coffee_seeds", "fruitfly", "fruitfly"},
	family_min_count = TUNING.FARM_PLANT_SAME_FAMILY_MIN,
	family_check_dist = TUNING.FARM_PLANT_SAME_FAMILY_RADIUS,
	stage_netvar = net_tinybyte,
	plantregistryinfo = plantregistryinfo,
	plantregistrywidget = "widgets/redux/farmplantpage",
	plantregistrysummarywidget = "widgets/redux/farmplantsummarywidget",
	pictureframeanim = {anim = "emoteXL_loop_dance0", time = 7*FRAMES},
	honor_plant = false,
	honor_weight = 0,
	terror_plant = true,
	terror_weight = 1,

	modded = true,
}

PLANT_DEFS.terror_hawthorn = {
	build = "farm_plant_terror_hawthorn",
	bank = "farm_plant_terror_hawthorn",
	grow_time = MakeGrowTimes(12 * TUNING.SEG_TIME, 16 * TUNING.SEG_TIME, 4 * TUNING.TOTAL_DAY_TIME, 7 * TUNING.TOTAL_DAY_TIME),
	moisture = {drink_rate = TUNING.FARM_PLANT_DRINK_LOW, min_percent = TUNING.FARM_PLANT_DROUGHT_TOLERANCE},
	nutrient_consumption = {0, M, M},
	nutrient_restoration = {true, nil, nil},
	max_killjoys_tolerance = TUNING.FARM_PLANT_KILLJOY_TOLERANCE,
	good_seasons = {autumn = true, winter = true},
	weight_data = {384.59, 662.77, .18},
	sounds = sounds,
	prefab = "farm_plant_terror_hawthorn",
	product = "terror_hawthorn",
	product_oversized = "terror_hawthorn_oversized",
	seed = "terror_hawthorn_seeds",
	plant_type_tag = "terror_hawthorn",
	loot_oversized_rot = {"spoiled_food", "spoiled_food", "spoiled_food", "terror_hawthorn_seeds", "fruitfly", "fruitfly"},
	family_min_count = TUNING.FARM_PLANT_SAME_FAMILY_MIN,
	family_check_dist = TUNING.FARM_PLANT_SAME_FAMILY_RADIUS,
	stage_netvar = net_tinybyte,
	plantregistryinfo = plantregistryinfo,
	plantregistrywidget = "widgets/redux/farmplantpage",
	plantregistrysummarywidget = "widgets/redux/farmplantsummarywidget",
	pictureframeanim = {anim = "emoteXL_loop_dance0", time = 7*FRAMES},
	honor_plant = false,
	honor_weight = 0,
	terror_plant = true,
	terror_weight = 1,

	modded = true,
}

PLANT_DEFS.terror_passionfruit = {
	build = "farm_plant_terror_passionfruit",
	bank = "farm_plant_terror_passionfruit",
	grow_time = MakeGrowTimes(12 * TUNING.SEG_TIME, 16 * TUNING.SEG_TIME, 4 * TUNING.TOTAL_DAY_TIME, 7 * TUNING.TOTAL_DAY_TIME),
	moisture = {drink_rate = TUNING.FARM_PLANT_DRINK_LOW, min_percent = TUNING.FARM_PLANT_DROUGHT_TOLERANCE},
	nutrient_consumption = {M, M, 0},
	nutrient_restoration = {nil, nil, true},
	max_killjoys_tolerance = TUNING.FARM_PLANT_KILLJOY_TOLERANCE,
	good_seasons = {winter = true, spring = true},
	weight_data = {384.59, 662.77, .18},
	sounds = sounds,
	prefab = "farm_plant_terror_passionfruit",
	product = "terror_passionfruit",
	product_oversized = "terror_passionfruit_oversized",
	seed = "terror_passionfruit_seeds",
	plant_type_tag = "terror_passionfruit",
	loot_oversized_rot = {"spoiled_food", "spoiled_food", "spoiled_food", "terror_passionfruit_seeds", "fruitfly", "fruitfly"},
	family_min_count = TUNING.FARM_PLANT_SAME_FAMILY_MIN,
	family_check_dist = TUNING.FARM_PLANT_SAME_FAMILY_RADIUS,
	stage_netvar = net_tinybyte,
	plantregistryinfo = plantregistryinfo,
	plantregistrywidget = "widgets/redux/farmplantpage",
	plantregistrysummarywidget = "widgets/redux/farmplantsummarywidget",
	pictureframeanim = {anim = "emoteXL_loop_dance0", time = 7*FRAMES},
	honor_plant = false,
	honor_weight = 0,
	terror_plant = true,
	terror_weight = 1,

	modded = true,
}

return SEEDS_DEFS
