local _G = GLOBAL
local STRINGS = _G.STRINGS

STRINGS.UI.COOKBOOK.TAB_TITLE_WHATTOEAT = "今天吃些啥"
STRINGS.UI.COOKBOOK.TAB_TITLE_HELPMECOOK = "帮我做大餐"

STRINGS.UI.COOKBOOK.FILTER_TITLE_MEAT = "种类："
STRINGS.UI.COOKBOOK.FILTER_MEATS = "肉食"
STRINGS.UI.COOKBOOK.FILTER_VEGGIES = "素食"
STRINGS.UI.COOKBOOK.FILTER_OTHERS = "零食"

STRINGS.UI.COOKBOOK.FILTER_TITLE_EFFECT = "特效："
STRINGS.UI.COOKBOOK.FILTER_SIDE_EFFECT = "有特效"
STRINGS.UI.COOKBOOK.FILTER_NO_EFFECT = "无特效"

STRINGS.UI.COOKBOOK.FILTER_TITLE_MOD = "模组："
STRINGS.UI.COOKBOOK.FILTER_IS_MOD = "模组"
STRINGS.UI.COOKBOOK.FILTER_NOT_MOD = "非模组"

STRINGS.UI.COOKBOOK.TITLE_COOKABLE_RECIPES = "可做食谱"

STRINGS.UI.COOKBOOK.EMPTY_PAGE_TITLE = "空空如也"
STRINGS.UI.COOKBOOK.EMPTY_PAGE_WORDS = "像我的肚子一样空~"

STRINGS.UI.COOKBOOK.SEP = "，"

STRINGS.UI.COOKBOOK.SIDE_EFFECT_SUB_TITLE = "食用特效"

STRINGS.UI.COOKBOOK.COOK_METHOD_SUB_TITLE = "烹饪方法"
STRINGS.UI.COOKBOOK.COOK_METHOD_COOKER_UNKNOWN = "？锅"
STRINGS.UI.COOKBOOK.COOK_METHOD_TIME_UNKNOWN = "？"
STRINGS.UI.COOKBOOK.COOK_METHOD_TIME_UNIT = "秒"
STRINGS.UI.COOKBOOK.COOK_METHOD_PRIORITY = "优先级"
STRINGS.UI.COOKBOOK.COOK_METHOD_PRIORITY_UNKNOWN = "？"

STRINGS.UI.COOKBOOK.COOK_RECIPE_SUB_TITLE = "烹饪配方"
STRINGS.UI.COOKBOOK.COOK_RECIPE_OR = " 或 "
STRINGS.UI.COOKBOOK.COOK_RECIPE_NO = "无"
STRINGS.UI.COOKBOOK.COOK_RECIPE_COOKED = "(烤)"
STRINGS.UI.COOKBOOK.COOK_RECIPE_DRIED = "(干)"
STRINGS.UI.COOKBOOK.COOK_RECIPE_BOTH = "(烤/干)"

STRINGS.UI.COOKBOOK.COOK_RECIPE = {}
--原版
STRINGS.UI.COOKBOOK.COOK_RECIPE.PHRASE = {}
STRINGS.UI.COOKBOOK.COOK_RECIPE.PHRASE.EEL = "(活/生/烤)鳗鱼"
STRINGS.UI.COOKBOOK.COOK_RECIPE.PHRASE.TRUNK = "(烤/冬/夏)象鼻"
--Heap of Food
STRINGS.UI.COOKBOOK.COOK_RECIPE.PHRASE.HOF = {}
STRINGS.UI.COOKBOOK.COOK_RECIPE.PHRASE.HOF.PLANTMEAT = "(烤/干)叶肉"

--原版
STRINGS.UI.COOKBOOK.COOK_RECIPE.CALIFORNIAROLL = "(烤/干)海带叶=2，鱼度≥1"  --加利福尼亚卷

--永不妥协
STRINGS.UI.COOKBOOK.COOK_RECIPE.UM = {}
STRINGS.UI.COOKBOOK.COOK_RECIPE.UM.UM_DEVILED_EGGS = "怪物度>蛋度\n无肉度"  --永不妥协 怪物蛋
STRINGS.UI.COOKBOOK.COOK_RECIPE.UM.FIGATONI = "(烤)无花果 或 蚜虫>0，菜度≥2\n昆虫度<1"  --永不妥协 原版 无花果意面

--Heap of Food
STRINGS.UI.COOKBOOK.COOK_RECIPE.HOF = {}
STRINGS.UI.COOKBOOK.COOK_RECIPE.HOF.CORNINCUP = "盐≥1，(烤)辣椒≥1，(烤)玉米≥1，黄油/酪度>0"  --Heap of Food 墨西哥玉米杯装

STRINGS.UI.COOKBOOK.COOK_RECIPE_UNKNOWN = "未知"

STRINGS.UI.COOKBOOK.HOVER_TITLE_WHATTOEAT = "让我看看能做啥……"
STRINGS.UI.COOKBOOK.HOVER_TITLE_WHATTOEAT_SPECIAL = "馨儿喵，告诉我吃啥！"

STRINGS.UI.COOKBOOK.BOOKMARK_HOVER = "刷新"

STRINGS.UI.COOKBOOK.SORT_THIRST = "口渴值"

-- STRINGS.ACTIONS.CASTSPELL.AUTO_COOK = "自动烹饪"
STRINGS.ACTIONS.CASTAOE.COOKBOOK = "自动烹饪"

STRINGS.UI.COOKBOOK.SPEECH = {
    NOVALIDCOOKER = "巧厨难为无“锅”之炊",
    ZERODONE = "巧厨难为无“米”之炊",
    LESSDONE = "材料只够做",
    LESSDONE_SURFIX = "份",
    INGNOTCHOOSE = "快去烹饪书中选择食材"
}

STRINGS.UI.COOKBOOK.SEARCH_TEXT = "搜索"
STRINGS.UI.COOKBOOK.SEARCH_TIP = "点击搜索 "
STRINGS.UI.COOKBOOK.SEARCHBAR_TEXT = "搜索想要的食材!"
STRINGS.UI.COOKBOOK.STEP_ONE_TITLE = "第一步"
STRINGS.UI.COOKBOOK.STEP_ONE_BODY = "选择食材"
STRINGS.UI.COOKBOOK.STEP_TWO_TITLE = "第二步"
STRINGS.UI.COOKBOOK.STEP_TWO_BODY = "选择烹饪锅"
STRINGS.UI.COOKBOOK.STEP_THREE_TITLE = "第三步"
STRINGS.UI.COOKBOOK.STEP_THREE_BODY = "确认烹饪结果"
STRINGS.UI.COOKBOOK.READ_BUTTON = "确认了？去读书！\n装备烹饪书，右键施法~"
STRINGS.UI.COOKBOOK.CURRENT_RECIPE = "当前配方："
STRINGS.UI.COOKBOOK.CURRENT_POT = "当前烹饪锅："
STRINGS.UI.COOKBOOK.PREDICT_FOOD = "预测烹饪结果："
STRINGS.UI.COOKBOOK.NONESTR = "无"
