-- 精炼材料科技削弱，草树枝芦苇木头大理石荧光果来源削弱
local refine_change = GetModConfigData("refine_change")
local changeIndex = refine_change == -1 and 8 or 16

TUNING.GRASS_REGROW_TIME = TUNING.GRASS_REGROW_TIME * changeIndex
TUNING.SAPLING_REGROW_TIME = TUNING.SAPLING_REGROW_TIME * changeIndex
TUNING.MARSHBUSH_REGROW_TIME = TUNING.MARSHBUSH_REGROW_TIME * changeIndex
TUNING.REEDS_REGROW_TIME = TUNING.REEDS_REGROW_TIME * changeIndex
TUNING.GRASSGEKKO_REGROW_TIME = TUNING.GRASSGEKKO_REGROW_TIME * changeIndex

TUNING.EVERGREEN_GROW_TIME[1].base = TUNING.EVERGREEN_GROW_TIME[1].base * changeIndex
TUNING.EVERGREEN_GROW_TIME[1].random = TUNING.EVERGREEN_GROW_TIME[1].random * changeIndex
TUNING.EVERGREEN_GROW_TIME[2].base = TUNING.EVERGREEN_GROW_TIME[2].base * changeIndex
TUNING.EVERGREEN_GROW_TIME[2].random = TUNING.EVERGREEN_GROW_TIME[2].random * changeIndex
TUNING.EVERGREEN_GROW_TIME[3].base = TUNING.EVERGREEN_GROW_TIME[3].base * changeIndex
TUNING.EVERGREEN_GROW_TIME[3].random = TUNING.EVERGREEN_GROW_TIME[3].random * changeIndex
TUNING.EVERGREEN_GROW_TIME[4].base = TUNING.EVERGREEN_GROW_TIME[4].base * changeIndex
TUNING.EVERGREEN_GROW_TIME[4].random = TUNING.EVERGREEN_GROW_TIME[4].random * changeIndex

TUNING.TWIGGY_TREE_GROW_TIME[1].base = TUNING.TWIGGY_TREE_GROW_TIME[1].base * changeIndex
TUNING.TWIGGY_TREE_GROW_TIME[1].random = TUNING.TWIGGY_TREE_GROW_TIME[1].random * changeIndex
TUNING.TWIGGY_TREE_GROW_TIME[2].base = TUNING.TWIGGY_TREE_GROW_TIME[2].base * changeIndex
TUNING.TWIGGY_TREE_GROW_TIME[2].random = TUNING.TWIGGY_TREE_GROW_TIME[2].random * changeIndex
TUNING.TWIGGY_TREE_GROW_TIME[3].base = TUNING.TWIGGY_TREE_GROW_TIME[3].base * changeIndex
TUNING.TWIGGY_TREE_GROW_TIME[3].random = TUNING.TWIGGY_TREE_GROW_TIME[3].random * changeIndex
TUNING.TWIGGY_TREE_GROW_TIME[4].base = TUNING.TWIGGY_TREE_GROW_TIME[4].base * changeIndex
TUNING.TWIGGY_TREE_GROW_TIME[4].random = TUNING.TWIGGY_TREE_GROW_TIME[4].random * changeIndex

TUNING.DECIDUOUS_GROW_TIME[1].base = TUNING.DECIDUOUS_GROW_TIME[1].base * changeIndex
TUNING.DECIDUOUS_GROW_TIME[1].random = TUNING.DECIDUOUS_GROW_TIME[1].random * changeIndex
TUNING.DECIDUOUS_GROW_TIME[2].base = TUNING.DECIDUOUS_GROW_TIME[2].base * changeIndex
TUNING.DECIDUOUS_GROW_TIME[2].random = TUNING.DECIDUOUS_GROW_TIME[2].random * changeIndex
TUNING.DECIDUOUS_GROW_TIME[3].base = TUNING.DECIDUOUS_GROW_TIME[3].base * changeIndex
TUNING.DECIDUOUS_GROW_TIME[3].random = TUNING.DECIDUOUS_GROW_TIME[3].random * changeIndex
TUNING.DECIDUOUS_GROW_TIME[4].base = TUNING.DECIDUOUS_GROW_TIME[4].base * changeIndex
TUNING.DECIDUOUS_GROW_TIME[4].random = TUNING.DECIDUOUS_GROW_TIME[4].random * changeIndex

TUNING.MARBLESHRUB_GROW_TIME[1].base = TUNING.MARBLESHRUB_GROW_TIME[1].base * changeIndex / 4
TUNING.MARBLESHRUB_GROW_TIME[1].random = TUNING.MARBLESHRUB_GROW_TIME[1].random * changeIndex / 4
TUNING.MARBLESHRUB_GROW_TIME[2].base = TUNING.MARBLESHRUB_GROW_TIME[2].base * changeIndex / 4
TUNING.MARBLESHRUB_GROW_TIME[2].random = TUNING.MARBLESHRUB_GROW_TIME[2].random * changeIndex / 4
TUNING.MARBLESHRUB_GROW_TIME[3].base = TUNING.MARBLESHRUB_GROW_TIME[3].base * changeIndex / 2
TUNING.MARBLESHRUB_GROW_TIME[3].random = TUNING.MARBLESHRUB_GROW_TIME[3].random * changeIndex / 2

TUNING.WINTER_TREE_GROW_TIME[1].base = TUNING.WINTER_TREE_GROW_TIME[1].base * changeIndex
TUNING.WINTER_TREE_GROW_TIME[1].random = TUNING.WINTER_TREE_GROW_TIME[1].random * changeIndex
TUNING.WINTER_TREE_GROW_TIME[2].base = TUNING.WINTER_TREE_GROW_TIME[2].base * changeIndex
TUNING.WINTER_TREE_GROW_TIME[2].random = TUNING.WINTER_TREE_GROW_TIME[2].random * changeIndex
TUNING.WINTER_TREE_GROW_TIME[3].base = TUNING.WINTER_TREE_GROW_TIME[3].base * changeIndex
TUNING.WINTER_TREE_GROW_TIME[3].random = TUNING.WINTER_TREE_GROW_TIME[3].random * changeIndex
TUNING.WINTER_TREE_GROW_TIME[4].base = TUNING.WINTER_TREE_GROW_TIME[4].base * changeIndex
TUNING.WINTER_TREE_GROW_TIME[4].random = TUNING.WINTER_TREE_GROW_TIME[4].random * changeIndex
TUNING.WINTER_TREE_GROW_TIME[5].base = TUNING.WINTER_TREE_GROW_TIME[5].base * changeIndex
TUNING.WINTER_TREE_GROW_TIME[5].random = TUNING.WINTER_TREE_GROW_TIME[5].random * changeIndex

TUNING.LIGHTFLIER_FLOWER_REGROW_TIME = TUNING.LIGHTFLIER_FLOWER_REGROW_TIME * changeIndex
TUNING.LIGHTFLIER_FLOWER.REGROW_TIME = TUNING.LIGHTFLIER_FLOWER.REGROW_TIME * changeIndex
TUNING.FLOWER_CAVE_REGROW_TIME = TUNING.FLOWER_CAVE_REGROW_TIME * changeIndex
